import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.shared.models import TenantBase


class Notification(TenantBase):
    """In-app notification for a user.

    Generated by scheduler jobs (deadline checks, verjaring warnings, task status changes)
    and consumed by the frontend bell icon in the header.
    """

    __tablename__ = "notifications"

    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("users.id"),
        nullable=False,
    )
    type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )  # deadline_approaching, deadline_overdue, verjaring_warning, task_assigned, etc.
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False, default="")
    case_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        ForeignKey("cases.id"),
        nullable=True,
    )
    case_number: Mapped[str | None] = mapped_column(String(50), nullable=True)
    task_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid,
        nullable=True,
    )
    is_read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    # FEAT-AI-05: when set in the future, the CaseActionFeed hides this item under
    # the "Wachtend" filter until this moment passes. NULL = not snoozed. Snoozing
    # never marks the item read — it stays actionable, just temporarily hidden.
    snoozed_until: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        Index("ix_notifications_user_unread", "tenant_id", "user_id", "is_read", "created_at"),
    )
