"""Follow-up recommendation models — rules-based workflow advisor for incasso cases."""

import uuid
from datetime import datetime
from decimal import Decimal
from enum import StrEnum

from sqlalchemy import DateTime, ForeignKey, Integer, Numeric, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.shared.models import TenantBase


class RecommendationStatus(StrEnum):
    """Status of a follow-up recommendation through the review workflow."""

    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTED = "executed"


class RecommendedAction(StrEnum):
    """Actions the follow-up advisor can recommend."""

    GENERATE_DOCUMENT = "generate_document"
    ESCALATE = "escalate"


# Dutch display labels
ACTION_LABELS: dict[str, str] = {
    "generate_document": "Document genereren & versturen",
    "escalate": "Handmatige beoordeling nodig",
}

URGENCY_LABELS: dict[str, str] = {
    "normal": "Klaar voor actie",
    "overdue": "Te laat",
}


class FollowupRecommendation(TenantBase):
    """A rules-based follow-up recommendation for an incasso case.

    Generated by the scheduled scanner when a case has been in a pipeline step
    long enough (deadline_status = orange or red). Lawyer reviews and approves
    with 1 click, then the system executes (generates document, sends email,
    advances pipeline step).
    """

    __tablename__ = "followup_recommendations"

    # Case + step context (snapshot at time of recommendation)
    case_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("cases.id", ondelete="CASCADE"), nullable=False, index=True
    )
    incasso_step_id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        ForeignKey("incasso_pipeline_steps.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Recommendation
    recommended_action: Mapped[str] = mapped_column(String(50), nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False)
    days_in_step: Mapped[int] = mapped_column(Integer, nullable=False)
    outstanding_amount: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)
    urgency: Mapped[str] = mapped_column(
        String(20), nullable=False, default="normal"
    )  # "normal" (orange) or "overdue" (red)

    # Review
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, default=RecommendationStatus.PENDING
    )
    reviewed_by_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id"), nullable=True
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    review_note: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Execution result
    executed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    execution_result: Mapped[str | None] = mapped_column(Text, nullable=True)
    generated_document_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("generated_documents.id"), nullable=True
    )

    # Relationships
    case: Mapped["Case"] = relationship("Case", lazy="selectin")  # noqa: F821
    incasso_step: Mapped["IncassoPipelineStep"] = relationship(  # noqa: F821
        "IncassoPipelineStep", lazy="selectin"
    )
    reviewed_by: Mapped["User | None"] = relationship(  # noqa: F821
        "User", lazy="selectin"
    )
    generated_document: Mapped["GeneratedDocument | None"] = relationship(  # noqa: F821
        "GeneratedDocument", lazy="selectin"
    )
